name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --verbose -- --check
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Run Rust tests
      run: cargo test --workspace --verbose


  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Rust tests
      run: cargo test --workspace --verbose
